title: Rice University Astroparticle  Group
description: >
  We conduct cutting-edge research at the interface of astroparticle physics and translational computer science.
theme: jekyll-theme-cayman
url: "https://riceastroparticlelab.github.io"
author: Computational Astroparticle Group
