title: Rice University Astroparticle  Group
description: >
  Computational Astroparticle Group conducts cutting-edge research at the interface of astroparticle physics and computer science.
theme: jekyll-theme-cayman
url: "https://riceastroparticlelab.github.io"
author: Computational Astroparticle Group
